### ISSUE TITLE
Issue with Python distribution on Windows 10 with default init pyapp.

### ISSUE THREAD

**Issue by McSpidey** [indygreg/PyOxidizer#28]
Hi

Firstly, thanks for this great tool - it's exactly what I've wanted to join the worlds of Rust and Python and I can't wait to get it going!

pyoxidizer itself builds fine, both via crate and the github master build, but I'm having an issue with the stand-alone python aspect on Windows 10 it sems. Here's the logs trying to build the default in init pyapp example.

```
...pyapp>pyoxidizer build
no existing PyOxidizer artifacts found
processing config file ...pyapp\pyoxidizer.toml
resolving Python distribution...
downloading https://github.com/indygreg/python-build-standalone/releases/download/20190617/cpython-3.7.3-windows-amd64-20190618T0516.tar.zst
Python distribution available at ...pyapp\build\target\x86_64-pc-windows-msvc\debug\pyoxidizer\cpython-3.7.3-windows-amd64-20190618T0516.tar.zst
reading data from Python distribution...
thread 'main' panicked at 'unable to extract tar archive: Custom { kind: NotFound, error: TarError { desc: "failed to unpack `...pyapp\\build\\target\\x86_64-pc-windows-msvc\\debug\\pyoxidizer\\python.fd43554b5654\\python\\install\\Lib\\site-packages\\pip-19.1.1-py3.7.egg\\pip\\_vendor\\urllib3\\contrib\\_securetransport\\__pycache__\\low_level.cpython-37.pyc`", io: Custom { kind: NotFound, error: TarError { desc: "failed to unpack `python/install/Lib/site-packages/pip-19.1.1-py3.7.egg/pip/_vendor/urllib3/contrib/_securetransport/_` into `...pyapp\\build\\target\\x86_64-pc-windows-msvc\\debug\\pyoxidizer\\python.fd43554b5654\\python\\install\\Lib\\site-packages\\pip-19.1.1-py3.7.egg\\pip\\_vendor\\urllib3\\contrib\\_securetransport\\__pycache__\\low_level.cpython-37.pyc`", io: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." } } } } }', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```
---
Backtrace enabled Version:

```
pyoxidizer build
no existing PyOxidizer artifacts found
processing config file ...pyapp\pyoxidizer.toml
resolving Python distribution...
Python distribution available at ...pyapp\build\target\x86_64-pc-windows-msvc\debug\pyoxidizer\cpython-3.7.3-windows-amd64-20190618T0516.tar.zst
reading data from Python distribution...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "unable to read Python license"', src\libcore\result.rs:997:5
stack backtrace:
   0: git_packbuilder_object_count
   1: git_packbuilder_object_count
   2: git_packbuilder_object_count
   3: git_packbuilder_object_count
   4: git_packbuilder_object_count
   5: git_packbuilder_object_count
   6: git_packbuilder_object_count
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: git_packbuilder_object_count
  16: git_packbuilder_object_count
  17: git_packbuilder_object_count
  18: <unknown>
  19: git_libgit2_version
  20: BaseThreadInitThunk
  21: RtlUserThreadStart
```

Any tips or pointers on this would be appreciated. Thanks!

**Comment by 0xf0f** [comment]
same issue here, win 10 pro x64

**Comment by jroggeman** [comment]
I'm seeing the issue as well on Windows 10 Enterprise.

using rustc 1.35.0 (3c235d560 2019-05-20).

```
λ  pyoxidizer build
no existing PyOxidizer artifacts found
processing config file C:/Users/jorogg/Code/kubernetes-util/bootstrapper\pyoxidizer.toml
resolving Python distribution...
downloading https://github.com/indygreg/python-build-standalone/releases/download/20190617/cpython-3.7.3-windows-amd64-20190618T0516.tar.zst
Python distribution available at C:/Users/jorogg/Code/kubernetes-util/bootstrapper\build\target\x86_64-pc-windows-msvc\debug\pyoxidizer\cpython-3.7.3-windows-amd64-20190618T0516.tar.zst
reading data from Python distribution...
thread 'main' panicked at 'unable to extract tar archive: Custom { kind: NotFound, error: TarError { desc: "failed to unpack `C:/Users/jorogg/Code/kubernetes-util/bootstrapper\\build\\target\\x86_64-pc-windows-msvc\\debug\\pyoxidizer\\python.fd43554b5654\\python\\install\\Lib\\site-packages\\pip-19.1.1-py3.7.egg\\pip\\_vendor\\urllib3\\packages\\ssl_match_hostname\\__pycache__\\__init__.cpython-37.pyc`", io: Custom { kind: NotFound, error: TarError { desc: "failed to unpack `python/install/Lib/site-packages/pip-19.1.1-py3.7.egg/pip/_vendor/urllib3/packages/ssl_match_hostnam` into `C:/Users/jorogg/Code/kubernetes-util/bootstrapper\\build\\target\\x86_64-pc-windows-msvc\\debug\\pyoxidizer\\python.fd43554b5654\\python\\install\\Lib\\site-packages\\pip-19.1.1-py3.7.egg\\pip\\_vendor\\urllib3\\packages\\ssl_match_hostname\\__pycache__\\__init__.cpython-37.pyc`", io: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." } } } } }', src\libcore\result.rs:997:5```

**Comment by indygreg** [comment]
I think this is a path length issue because I ran into something like it a few weeks ago :/

Could you please try creating a new application under `c:/myapp` or something to help test my theory?

If it is a path length issue, this could be... not fun to fix. But we should at least have a better user experience. In my mind, that means detecting when the path will be too long and failing with a clear error message. That would be a stop-gap until we handle full length paths.

**Comment by McSpidey** [comment]
Confirmed, it's working fine when in a shorter path.

**Comment by Tipuch** [comment]
This pull request should resolve the issues for longer paths (according to https://doc.rust-lang.org/std/fs/fn.canonicalize.html)
I've tested it on windows 10 pro and it worked nicely, feel free to test it.

**Comment by Luckz** [comment]
Is this also a lack of
```
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]
"LongPathsEnabled"=dword:00000001
```
?

**Comment by Fondor1** [comment]
> 
> 
> Is this also a lack of
> 
> ```
> Windows Registry Editor Version 5.00
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]
> "LongPathsEnabled"=dword:00000001
> ```
> 
> ?

I have this key set as indicated but still experience the issue without applying the fix.

**Comment by indygreg** [comment]
Could someone please install PyOxidizer 0.2.0 (`cargo install --force pyoxidizer`) and report if they still see this issue?

(I wouldn't be surprised if it still occurs. I would like to know where it is failing now, though.)

**Comment by McSpidey** [comment]
I just tried this and re-created the "Your First PyOxidizer Project" steps in the original long path location, it compiled and executed REPL just fine. I'll close this ticket.
