### ISSUE TITLE
Failure to build when module_search_paths contain backslashes

### ISSUE THREAD

**Issue by wkschwartz** [indygreg/PyOxidizer#321]
161f76869b9308cc8626e8d25d857ab16c2fae84 appears to have missed a spot: serializing `config.module_search_paths ` doesn't take advantage of `optional_pathbuf_to_string`:
https://github.com/indygreg/PyOxidizer/blob/3e19b5bf1e05bcb9850effbbcd6bbd78cc388d57/pyoxidizer/src/py_packaging/config.rs#L273-L274

I *think* (I'm a Rust neophyte) that the fix is to replace the above with
```rust
|p| optional_pathbuf_to_string(&Some(p))
```
(I [believe](https://github.com/indygreg/PyOxidizer/blob/3e19b5bf1e05bcb9850effbbcd6bbd78cc388d57/python-packaging/src/interpreter.rs#L447) that `p: std::path::PathBuf` above.)

<details>
<summary>Test case</summary>

Copy the following to `pyoxidizer.bzl` in an otherwise empty directory.

```bzl
def make():
    dist = default_python_distribution()
    python_config = dist.make_python_interpreter_config()
    python_config.module_search_paths = ["$ORIGIN\\Lib\\site-packages"]
    exe = dist.to_python_executable(
        name="pyapp",
        packaging_policy=dist.make_python_packaging_policy(),
        config=python_config,
    )
    files = FileManifest()
    files.add_python_resource(".", exe)
    return files
register_target("install", make, default=True)
resolve_targets()
```
</details>

<details>
<summary>Error message from test case</summary>

Result of running `pyoxidizer build`. Paths shortened for brevity. This is running on Windows 10 with PyOxidizer 0.9.0 with rustc 1.47.0 (18bf6b4f0 2020-10-07) stable-x86_64-pc-windows-msvc.

```
<SNIP>
   Compiling python-packaging v0.2.0
   Compiling pyapp v0.1.0 ($TEMP\pyoxidizer.OEtkUtlV1K8j\pyapp)
   Compiling python3-sys v0.5.1
error: unknown character escape: L
  --> $TEMP\pyoxidizer.OEtkUtlV1K8j\artifacts\default_python_config.rs:44:78
   |
44 |             module_search_paths: Some(vec![std::path::PathBuf::from("$ORIGIN\Lib\site-packages")]),
   |                                                                              ^ unknown character escape

error: unknown character escape: s
  --> $TEMP\pyoxidizer.OEtkUtlV1K8j\artifacts\default_python_config.rs:44:82
   |
44 |             module_search_paths: Some(vec![std::path::PathBuf::from("$ORIGIN\Lib\site-packages")]),
   |                                                                                  ^ unknown character escape

error: aborting due to 2 previous errors

error: could not compile `pyapp`.

To learn more, run the command again with --verbose.
error[PYOXIDIZER_BUILD]: command ["cargo", "build", "--target", "x86_64-pc-windows-msvc", "--target-dir", "$TEMP\\pyoxidizer.OEtkUtlV1K8j\\build\\target", "--bin", "pyapp", "--no-default-features", "--features", "build-mode-prebuilt-artifacts cpython-link-default"] exited with code 101
  --> .\pyoxidizer.bzl:11:5
   |
11 |     files.add_python_resource(".", exe)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ add_python_resource


error: command ["cargo", "build", "--target", "x86_64-pc-windows-msvc", "--target-dir", "$TEMP\\pyoxidizer.OEtkUtlV1K8j\\build\\target", "--bin", "pyapp", "--no-default-features", "--features", "build-mode-prebuilt-artifacts cpython-link-default"] exited with code 101
```
</details>

A test case should be added like [this one](https://github.com/indygreg/PyOxidizer/blob/3e19b5bf1e05bcb9850effbbcd6bbd78cc388d57/pyoxidizer/src/py_packaging/config.rs#L375-L386) but using backslashes.

**Comment by indygreg** [comment]
Thanks for the report.

This is likely a pre-existing bug due to failing to escape `\`.

You can work around by using `/` as the path delimiter. (Windows APIs and Rust's `Path` types should respect `/` as a path delimiter on Windows.)

**Comment by indygreg** [comment]
I think the commit I just pushed fixes this! Would you be willing to install from the `main` branch to verify?

`cargo install --git https://github.com/indygreg/PyOxidizer.git --branch main pyoxidizer`

**Comment by wkschwartz** [comment]
93af627 did not fix `module_search_paths`, so I think you should reopen this ticket. The test in my OP still fails. As with 161f768, 93af627 just affects serialization of `PathBuf`s other than those contained in `module_search_paths`. I submitted PR #327 to fix `module_search_paths`. The PR adds a test similar to the one in my OP. I also manually ran the test in my OP using the PR and building finishes successfully now.
