### ISSUE TITLE
Cannot run default project from `init-config-file` and no stack trace

### ISSUE THREAD

**Issue by layday** [indygreg/PyOxidizer#380]
Attempting to build a newly-created project from `init-config-file`, on macOS 10.14 and with pyoxidizer 0.11.0, with `run` produces:

```
error[PYOXIDIZER_PYTHON_EXECUTABLE]: could not execute command: No such file or directory (os error 2)

Caused by:
    No such file or directory (os error 2)
   --> ./pyoxidizer.bzl:270:5
    |
270 |     files.add_python_resource(".", exe)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ to_file_manifest()


error: could not execute command: No such file or directory (os error 2)

Caused by:
    No such file or directory (os error 2)
```

I assume it's the exe that it can't find but there's not much in the way of a stack trace that would allow me to dig deeper into the issue.

**Comment by indygreg** [comment]
Hmm. This is a weird one. Thanks for the support. Let me sprinkle some more error contexts in the code to help debug this. (My guess is it can't find a `cargo` executable in `PATH`.)

**Comment by julienfr112** [comment]
Can I help you in any way to solve that ?

**Comment by indygreg** [comment]
There are a few issues tracking this bug. The good news is I fixed it yesterday in commit e23a3f996acf74efdb2f4960273fce1049b14e0e. I attributed that to issue #390 because it was the issue I saw at the time. I'm hoping to officially release the next version today. But you can generally safely run PyOxidizer from the latest commit in the `main` branch.

**Comment by layday** [comment]
Thanks for looking into this. It's still happening with 0.14.1 for me:

```
[...]
libpythonXY created
locating Apple SDK macosx11.1+ supporting macosx10.9
using SDK /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk (macosx11.3 targeting macosx10.9)
building with Rust 1.51.0
error: could not execute process `rustc -vV` (never executed)

Caused by:
  No such file or directory (os error 2)
error[PYOXIDIZER_PYTHON_EXECUTABLE]: adding PythonExecutable to FileManifest

Caused by:
    0: building Python executable
    1: building executable with Rust project
    2: command ["/Users/abc/Library/Caches/pyoxidizer/rust/1.51.0-x86_64-apple-darwin/bin/cargo", "build", "--target", "x86_64-apple-darwin", "--target-dir", "/tmp/pyoxidizerh1rrFg/build/target", "--bin", "pyapp", "--locked", "--no-default-features", "--features", "build-mode-prebuilt-artifacts cpython-link-unresolved-static global-allocator-jemalloc allocator-jemalloc"] exited with code 101
   --> ./pyoxidizer.bzl:271:5
    |
271 |     files.add_python_resource(".", exe)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ PythonExecutable.to_file_manifest()


error: adding PythonExecutable to FileManifest

Caused by:
    0: building Python executable
    1: building executable with Rust project
    2: command ["/Users/abc/Library/Caches/pyoxidizer/rust/1.51.0-x86_64-apple-darwin/bin/cargo", "build", "--target", "x86_64-apple-darwin", "--target-dir", "/tmp/pyoxidizerh1rrFg/build/target", "--bin", "pyapp", "--locked", "--no-default-features", "--features", "build-mode-prebuilt-artifacts cpython-link-unresolved-static global-allocator-jemalloc allocator-jemalloc"] exited with code 101
```

**Comment by layday** [comment]
Still experiencing this with 0.15.0.  Please let me know if there's anything I can do to help with debugging.

**Comment by indygreg** [comment]
This is most peculiar. I suspect this is a `PATH` issue. Specifically, we don't add the directory with our managed Rust toolchain to `PATH`. That is resulting in `cargo` not being able to find `rustc`.

Let me take a peek at cargo's logic for finding `rustc` and see what we should do...

**Comment by indygreg** [comment]
The commit I just pushed _might_ fix this. You should be able to download a pre-built `pyoxidizer` binary from https://github.com/indygreg/PyOxidizer/actions/runs/818793654 in ~1 hour (CI seems to be running a bit slow today).

If you could report your feedback with that build, it would be most appreciated, @layday.

**Comment by layday** [comment]
Thanks, it seem to get a little further now - cargo reports it can't update a lock file and the build then fails with the same message:

```
[...]
locating Apple SDK macosx11.1+ supporting macosx10.9
using SDK /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk (macosx11.3 targeting macosx10.9)
building with Rust 1.52.0
    Updating git repository `https://github.com/indygreg/PyOxidizer.git`
error: the lock file /private/tmp/pyoxidizerYduzja/pyapp/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, use the --offline flag.
error[PYOXIDIZER_PYTHON_EXECUTABLE]: adding PythonExecutable to FileManifest

Caused by:
    0: building Python executable
    1: building executable with Rust project
    2: reading cargo output
    3: command ["/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/bin/cargo", "build", "--target", "x86_64-apple-darwin", "--target-dir", "/tmp/pyoxidizerYduzja/build/target", "--bin", "pyapp", "--locked", "--no-default-features", "--features", "build-mode-prebuilt-artifacts cpython-link-unresolved-static global-allocator-jemalloc allocator-jemalloc"] exited with code 101
   --> ./pyoxidizer.bzl:271:5
    |
271 |     files.add_python_resource(".", exe)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ PythonExecutable.to_file_manifest()


error: adding PythonExecutable to FileManifest

Caused by:
    0: building Python executable
    1: building executable with Rust project
    2: reading cargo output
    3: command ["/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/bin/cargo", "build", "--target", "x86_64-apple-darwin", "--target-dir", "/tmp/pyoxidizerYduzja/build/target", "--bin", "pyapp", "--locked", "--no-default-features", "--features", "build-mode-prebuilt-artifacts cpython-link-unresolved-static global-allocator-jemalloc allocator-jemalloc"] exited with code 101
```

**Comment by indygreg** [comment]
OK. I think I fixed that subsequent `Cargo.lock` issue. Please give CI a few minutes to build binaries and try again.

I believe this `Cargo.lock` issue would only occur on `pyoxidizer` binaries built by the `release` workflow in CI and maybe through `cargo install pyoxidizer --git ...`: it likely didn't occur for local builds from Git checkouts, which is why I didn't see it.

**Comment by layday** [comment]
Thanks, that did it, although now I'm getting a bunch of unrelated linker errors originating from pyembed:

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-arch" "x86_64" "-L" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.140hovi6u2l1k2rg.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.1g7athz24pnv6qyk.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.26ufwhtrpdlvo0qu.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.2foxotd7qujumhcx.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.303672peq7itv1y2.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.31uhtvwz3dh7c90g.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.38w4ycw6unqmrbk6.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.3alf14gz6rgo5m5q.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.3kkmrzq9p23njs2b.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.4b13cbhh2vryb956.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.4ecmytc1ck022m5o.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.4jz3cowixq8f2w73.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.4o8fw99culu69kwf.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.51ux4yvw0yuel5jk.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.51y5k22jbgd70ngh.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.5701iiv1hrhcnbed.rcgu.o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.ga79lifmg9ivv87.rcgu.o" "-o" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/pyapp.20sr7r47pre9985k.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps" "-L" "/tmp/pyoxidizerRS6xcu/build/target/debug/deps" "-L" "/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/build/jemalloc-sys-312418ed4882a5cd/out/build/lib" "-L" "/nix/store/47vpv5i10dwfg1cf5wca1k40f982g5fm-clang-wrapper-7.1.0/resource-root/lib/darwin" "-L" "/tmp/pyoxidizer-build-exe-packagingaMQcPx" "-L" "/Users/abc/Library/Caches/pyoxidizer/python_distributions/python.27f5ef23c513/python/build/lib" "-L" "/tmp/pyoxidizerRS6xcu/artifacts" "-L" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libjemallocator-ffcaaa1d60cb0082.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libpyembed-f25362b81b52d3b7.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libmemmap-49e5792f119b7c1e.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libjemalloc_sys-d8226214eb839e5c.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libdunce-6416d8d5a33c4e46.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libcpython-227734d0ef09c368.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libnum_traits-0c21128d0503e5bf.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libpython_packaging-d8eaf26fbc4370d8.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libitertools-0c08b9ff64391ffc.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libeither-ff774815027d0546.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libwalkdir-f5cb8d489dc61934.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libsame_file-5b5429ca63d62d79.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libpython_packed_resources-2e06f0ab5d83d529.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libonce_cell-79a5b1f672af7bf0.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libmailparse-938122d7993789f4.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libquoted_printable-6ba4ff1a2e6e6be8.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libcharset-2f94fa6a0a2097bd.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libencoding_rs-b52d34a628163212.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libcfg_if-27567a9a0c84c77a.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libbase64-a7a0593c7d5e78b2.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libbase64-5ffd08f9b659585b.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libtugger_licensing-d87f3e3967fe887a.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libspdx-862bd71f9f1ea2dd.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libregex-df2ce7744ea27019.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libaho_corasick-05a706a1fa1490bc.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libmemchr-0372da8d5973f7c9.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libregex_syntax-54d303f5160daa38.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/liblazy_static-ea43bf1fa0890d3c.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libsmallvec-75e6bd92d721eac6.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libtugger_file_manifest-46207ecd37da2f4f.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libbyteorder-f40960bff8ca4f6b.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libanyhow-ff5c2adf7a5a1a35.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/libpython3_sys-665f5b54bcfb6004.rlib" "/private/tmp/pyoxidizerRS6xcu/build/target/x86_64-apple-darwin/debug/deps/liblibc-29fd9e6520566ec0.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-03b7cc8bb9584efc.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-43536cfc9c9c300b.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libobject-bfb93f6c6a903396.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-d52ee6765e48d9ae.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgimli-b56132c9450bbaec.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-ed4cd0fbab7349ac.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-7a404b4047191342.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-f401a975d7880a1f.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-d9dee5a9f052ffe0.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-c73f1ebf99827aaf.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-b612ef1ed5c9489f.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-0498d3220acc297c.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-da050587f0859a64.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-bc5bda1ff8b653f1.rlib" "/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-f86ac61d31791301.rlib" "-framework" "AppKit" "-framework" "ApplicationServices" "-framework" "Carbon" "-framework" "CoreFoundation" "-framework" "CoreGraphics" "-framework" "CoreServices" "-framework" "IOKit" "-framework" "SystemConfiguration" "-ldl" "-lm" "-lncurses" "-lclang_rt.osx" "-lpthread" "-liconv" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-rdynamic"
  = note: ld: warning: directory not found for option '-L/tmp/pyoxidizer-build-exe-packagingaMQcPx'
          Undefined symbols for architecture x86_64:
            "_NSDefaultRunLoopMode", referenced from:
                _GetRunLoopMode in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXNotify.o)
            "_OBJC_CLASS_$_NSRunLoop", referenced from:
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXNotify.o)
            "_OBJC_CLASS_$_NSData", referenced from:
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXCursor.o)
            "_OBJC_CLASS_$_NSArray", referenced from:
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXDialog.o)
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXKeyEvent.o)
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXMenus.o)
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXClipboard.o)
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXServices.o)
            "_OBJC_CLASS_$_NSURL", referenced from:
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXDialog.o)
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXHLEvents.o)
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXBitmap.o)
            "_OBJC_CLASS_$_NSMutableDictionary", referenced from:
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXDialog.o)
            "_OBJC_CLASS_$_NSDictionary", referenced from:
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXDialog.o)
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXInit.o)
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXFont.o)
            "_OBJC_CLASS_$_NSUserDefaults", referenced from:
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXInit.o)
            "_OBJC_CLASS_$_NSMutableArray", referenced from:
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXDialog.o)
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXKeyEvent.o)
            "_OBJC_CLASS_$_NSDate", referenced from:
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXDialog.o)
                objc-class-ref in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXNotify.o)
            "_NSAppearanceNameDarkAqua", referenced from:
                _TkUnsupported1ObjCmd in libpyembed-f25362b81b52d3b7.rlib(tkMacOSXWm.o)
            "_utimensat", referenced from:
                _utime_nofollow_symlinks in libpyembed-f25362b81b52d3b7.rlib(posixmodule.o)
                _utime_dir_fd in libpyembed-f25362b81b52d3b7.rlib(posixmodule.o)
                _utime_default in libpyembed-f25362b81b52d3b7.rlib(posixmodule.o)
            "_futimens", referenced from:
                _utime_fd in libpyembed-f25362b81b52d3b7.rlib(posixmodule.o)
            "___isPlatformVersionAtLeast", referenced from:
                _os_listdir in libpyembed-f25362b81b52d3b7.rlib(posixmodule.o)
                _os_mkdir in libpyembed-f25362b81b52d3b7.rlib(posixmodule.o)
                _os_rmdir in libpyembed-f25362b81b52d3b7.rlib(posixmodule.o)
                _os_open in libpyembed-f25362b81b52d3b7.rlib(posixmodule.o)
                _os_scandir in libpyembed-f25362b81b52d3b7.rlib(posixmodule.o)
                _posix_do_stat in libpyembed-f25362b81b52d3b7.rlib(posixmodule.o)
                _os_access_impl in libpyembed-f25362b81b52d3b7.rlib(posixmodule.o)
                ...
            "___darwin_check_fd_set_overflow", referenced from:
                _seq2set in libpyembed-f25362b81b52d3b7.rlib(selectmodule.o)
                _set2list in libpyembed-f25362b81b52d3b7.rlib(selectmodule.o)
                _QueueFileEvents in libpyembed-f25362b81b52d3b7.rlib(tclMacOSXNotify.o)
                _Tcl_CreateFileHandler in libpyembed-f25362b81b52d3b7.rlib(tclMacOSXNotify.o)
                _Tcl_DeleteFileHandler in libpyembed-f25362b81b52d3b7.rlib(tclMacOSXNotify.o)
                _TclUnixWaitForFile in libpyembed-f25362b81b52d3b7.rlib(tclMacOSXNotify.o)
                _NotifierThreadProc in libpyembed-f25362b81b52d3b7.rlib(tclMacOSXNotify.o)
                ...
          ld: symbol(s) not found for architecture x86_64
          clang-7: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: could not compile `pyapp`

To learn more, run the command again with --verbose.
error[PYOXIDIZER_PYTHON_EXECUTABLE]: adding PythonExecutable to FileManifest

Caused by:
    0: building Python executable
    1: building executable with Rust project
    2: reading cargo output
    3: command ["/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/bin/cargo", "build", "--target", "x86_64-apple-darwin", "--target-dir", "/tmp/pyoxidizerRS6xcu/build/target", "--bin", "pyapp", "--locked", "--no-default-features", "--features", "build-mode-prebuilt-artifacts cpython-link-unresolved-static global-allocator-jemalloc allocator-jemalloc"] exited with code 101
   --> ./pyoxidizer.bzl:271:5
    |
271 |     files.add_python_resource(".", exe)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ PythonExecutable.to_file_manifest()


error: adding PythonExecutable to FileManifest

Caused by:
    0: building Python executable
    1: building executable with Rust project
    2: reading cargo output
    3: command ["/Users/abc/Library/Caches/pyoxidizer/rust/1.52.0-x86_64-apple-darwin/bin/cargo", "build", "--target", "x86_64-apple-darwin", "--target-dir", "/tmp/pyoxidizerRS6xcu/build/target", "--bin", "pyapp", "--locked", "--no-default-features", "--features", "build-mode-prebuilt-artifacts cpython-link-unresolved-static global-allocator-jemalloc allocator-jemalloc"] exited with code 101

**Comment by indygreg** [comment]
Could you please copy and paste the output lines starting with `locating Apple SDK` and `using SDK`?

And are you using a Python 3.8 or 3.9 distribution?

**Comment by indygreg** [comment]
I think what's happening here is `cargo` isn't using the same Apple SDK that we've picked up. That or you have `SDKROOT` defined and are forcing PyOxidizer to use an older, incompatible Apple SDK.

**Comment by layday** [comment]
> Could you please copy and paste the output lines starting with `locating Apple SDK` and `using SDK`?

```
locating Apple SDK macosx11.1+ supporting macosx10.9
using SDK /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk (macosx11.3 targeting macosx10.9)
```

> And are you using a Python 3.8 or 3.9 distribution?

3.9.

----

I was running this is a nix shell environment which exposes frameworks selectively.  I'm not sure how linking to macOS frameworks works exactly but PyOxidizer does not pass `-framework Foundation` to `cc`, which appears to be the framework the missing symbols are defined in.

**Comment by indygreg** [comment]
I suspect nix is doing something funky with some of the system libraries. AFAICT every symbol starting at `utimensat` is defined in `System.Framework` / `libSystem.dylib`. And we see `libSystem.dylib` being pulled in from the linker invocation (`"-framework" "AppKit" "-framework" "ApplicationServices" "-framework" "Carbon" "-framework" "CoreFoundation" "-framework" "CoreGraphics" "-framework" "CoreServices" "-framework" "IOKit" "-framework" "SystemConfiguration" "-ldl" "-lm" "-lncurses" "-lclang_rt.osx" "-lpthread" "-liconv" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-rdynamic"`).

What's noteworthy is AFAICT all these missing `libSystem` symbols are only present in the macOS 11.0+ SDK. The reason PyOxidizer is searching for and validating the Apple SDK is because it knows there are symbol references in the Python distributions that require a newer Apple SDK to build with. (Although you can target down to macOS 10.9 - it's just a build-time SDK requirement.) All these checks were installed following investigation in #373.

What I find peculiar about this situation is that PyOxidizer is finding the macOS 11.3 SDK on your machine and subsequently setting `SDKROOT` so `cargo` should pick it up. Yet, when cargo goes to link `libSystem.dylib`, that `libSystem.dylib` appears to be from an older Apple SDK. So it appears that something somewhere isn't honoring `SDKROOT`. I suspect nix has patched clang or lld to ignore `SDKROOT`. So what ends up happening is we think we've found a sufficiently modern Apple SDK, we think we tell `cargo` and the linker to use it, but instead an older macOS SDK is being used.

So the question we need to answer is what is nix doing that is non-standard and how can we detect which Apple SDK it will use (so we can verify it for compatibility to avoid cryptic error messages like this) or how can we force it to use an SDK that we know will work.

**Comment by layday** [comment]
Nix seems to place its own clang on the path which sources includes from `$NIX_CFLAGS_COMPILE`.  The same's done for ld with `$NIX_LDFLAGS`.  If https://github.com/NixOS/nixpkgs/issues/116341 is up to date, then Nix uses version 10.12 of the Apple SDK.
