### ISSUE TITLE
pyyaml-specific issue on macOS 10.14?

### ISSUE THREAD

**Issue by davidbarsky** [indygreg/PyOxidizer#66]
Probably something wrong with my Mac, but I figured I'd throw this issue here anyways: 

```
  = note: "cc" "-m64" "-L" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/aws_sam_cli-a3959855efc7657a.1sc1fh8r0omqpqxh.rcgu.o" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/aws_sam_cli-a3959855efc7657a.1xzpn2w2nutigvw2.rcgu.o" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/aws_sam_cli-a3959855efc7657a.286fu02pcd7f518t.rcgu.o" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/aws_sam_cli-a3959855efc7657a.4f135zb8jd1v05t.rcgu.o" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/aws_sam_cli-a3959855efc7657a.5bmudiq7dfdipdls.rcgu.o" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/aws_sam_cli-a3959855efc7657a.b4t3x8h2fjmqy01.rcgu.o" "-o" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/aws_sam_cli-a3959855efc7657a" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/aws_sam_cli-a3959855efc7657a.19q6kv86wlm00u7u.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps" "-L" "/Users/dbarsky/Developer/aws-sam-cli/build/target/debug/deps" "-L" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/build/jemalloc-sys-dc3abd71829c069a/out/build/lib" "-L" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/pyoxidizer" "-L" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/libpyembed-e4372d97d05954b9.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/libuuid-375b760b87e3ac06.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/librand-4203506b7d767a66.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/librand_xorshift-5c8f9da664781146.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/librand_pcg-0766c0f43ad9c51b.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/librand_hc-c5b5c7fbab3bc5cd.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/librand_chacha-07b5b25d2ee32f5f.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/librand_isaac-306de0ce26723e53.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/librand_core-5a39cc71549676e3.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/librand_os-0cb48f746785ed39.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/librand_jitter-ff5764b667a519b5.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/librand_core-5edc7a95a5a3c3d5.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/libjemalloc_sys-21b591f34ae49f82.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/libcpython-56cc579a6af24208.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/libnum_traits-2bc027f172c8968c.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/libpython3_sys-078b1d5b7bfc4a76.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/liblibc-7df6be712b4f3dfd.rlib" "/Users/dbarsky/Developer/aws-sam-cli/build/target/x86_64-apple-darwin/debug/deps/libbyteorder-9b0a8f4aa2f221bf.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-ebf2c4fba300d33c.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-7229a2ed0a63ac57.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace-d667a1ed12c3225b.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace_sys-95c3fb787955f318.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-3e8385e4bf12ab62.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-d619a00da08140e9.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-54447d0954eb6d31.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-d418ac01cb8eb17e.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-b4b855a2a137e1da.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-dcca354f696a82cd.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-23a0b38b7b055bae.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-44d80a1ddf142ecf.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-cfa39344cede6f40.rlib" "/Users/dbarsky/.rustup/toolchains/nightly-2019-07-01-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-1a9e57c727fcf5e1.rlib" "-framework" "CoreFoundation" "-framework" "SystemConfiguration" "-ldl" "-lm" "-framework" "Security" "-lpthread" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
          Undefined symbols for architecture x86_64:
            "_yaml_get_version", referenced from:
                ___pyx_pw_5_yaml_3get_version in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_emitter_initialize", referenced from:
                ___pyx_pw_5_yaml_8CEmitter_1__init__ in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_emitter_set_output", referenced from:
                ___pyx_pw_5_yaml_8CEmitter_1__init__ in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_emitter_set_indent", referenced from:
                ___pyx_pw_5_yaml_8CEmitter_1__init__ in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_emitter_set_width", referenced from:
                ___pyx_pw_5_yaml_8CEmitter_1__init__ in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_parser_initialize", referenced from:
                ___pyx_pw_5_yaml_7CParser_1__init__ in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_parser_set_input", referenced from:
                ___pyx_pw_5_yaml_7CParser_1__init__ in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_parser_scan", referenced from:
                ___pyx_f_5_yaml_7CParser__scan in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_pw_5_yaml_7CParser_7raw_scan in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_parser_set_input_string", referenced from:
                ___pyx_pw_5_yaml_7CParser_1__init__ in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_parser_delete", referenced from:
                ___pyx_tp_dealloc_5_yaml_CParser in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_emitter_emit", referenced from:
                ___pyx_f_5_yaml_8CEmitter__serialize_node in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_pw_5_yaml_8CEmitter_7emit in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_pw_5_yaml_8CEmitter_9open in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_pw_5_yaml_8CEmitter_11close in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_pw_5_yaml_8CEmitter_13serialize in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_token_delete", referenced from:
                ___pyx_f_5_yaml_7CParser__scan in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_pw_5_yaml_7CParser_7raw_scan in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_sequence_end_event_initialize", referenced from:
                ___pyx_f_5_yaml_8CEmitter__object_to_event in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_f_5_yaml_8CEmitter__serialize_node in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_mapping_end_event_initialize", referenced from:
                ___pyx_f_5_yaml_8CEmitter__object_to_event in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_f_5_yaml_8CEmitter__serialize_node in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_sequence_start_event_initialize", referenced from:
                ___pyx_f_5_yaml_8CEmitter__object_to_event in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_f_5_yaml_8CEmitter__serialize_node in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_get_version_string", referenced from:
                ___pyx_pw_5_yaml_1get_version_string in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_emitter_delete", referenced from:
                ___pyx_tp_dealloc_5_yaml_CEmitter in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_stream_start_event_initialize", referenced from:
                ___pyx_f_5_yaml_8CEmitter__object_to_event in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_pw_5_yaml_8CEmitter_9open in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_stream_end_event_initialize", referenced from:
                ___pyx_f_5_yaml_8CEmitter__object_to_event in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_pw_5_yaml_8CEmitter_11close in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_emitter_set_unicode", referenced from:
                ___pyx_pw_5_yaml_8CEmitter_1__init__ in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_document_end_event_initialize", referenced from:
                ___pyx_f_5_yaml_8CEmitter__object_to_event in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_pw_5_yaml_8CEmitter_13serialize in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_mapping_start_event_initialize", referenced from:
                ___pyx_f_5_yaml_8CEmitter__object_to_event in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_f_5_yaml_8CEmitter__serialize_node in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_emitter_set_break", referenced from:
                ___pyx_pw_5_yaml_8CEmitter_1__init__ in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_emitter_set_canonical", referenced from:
                ___pyx_pw_5_yaml_8CEmitter_1__init__ in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_event_delete", referenced from:
                ___pyx_f_5_yaml_7CParser__parse in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_f_5_yaml_7CParser__compose_document in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_f_5_yaml_7CParser__compose_node in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_f_5_yaml_7CParser__compose_scalar_node in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_f_5_yaml_7CParser__compose_sequence_node in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_f_5_yaml_7CParser__compose_mapping_node in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_tp_dealloc_5_yaml_CParser in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ...
            "_yaml_alias_event_initialize", referenced from:
                ___pyx_f_5_yaml_8CEmitter__object_to_event in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_f_5_yaml_8CEmitter__serialize_node in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_document_start_event_initialize", referenced from:
                ___pyx_f_5_yaml_8CEmitter__object_to_event in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_pw_5_yaml_8CEmitter_13serialize in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_scalar_event_initialize", referenced from:
                ___pyx_f_5_yaml_8CEmitter__object_to_event in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_f_5_yaml_8CEmitter__serialize_node in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
            "_yaml_parser_parse", referenced from:
                ___pyx_f_5_yaml_7CParser__parse in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_f_5_yaml_7CParser__parse_next_event in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
                ___pyx_pw_5_yaml_7CParser_15raw_parse in libpyembed-e4372d97d05954b9.rlib(_yaml.0.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: Could not compile `aws-sam-cli`.

To learn more, run the command again with --verbose.
error: cargo build failed
```

I'm attempting to embed https://github.com/awslabs/aws-sam-cli. I'm guessing this is one of the [C extension module gotchas](https://pyoxidizer.readthedocs.io/en/latest/packaging_pitfalls.html#c-and-other-native-extension-modules)?

**Comment by indygreg** [comment]
Yes, the missing symbols are likely due to not linking extra libraries required by the C extension. I bet if you scroll through the build output you will see a warning about it.

I'll try to get extra library linking implemented in the next few hours...

**Comment by indygreg** [comment]
This should now be fixed on the `main` branch. Please reopen if you still run into problems with the `pyyaml` package's C extension.

Note that in its current form we'll incur a run-time shared library dependency on libraries required by C extensions. I left it as an open issue to improve the packaging rules to add controls around policies for library dependencies. Library dependencies are a complicated problem for distribution. But we can start by supporting linking them and this should now be possible on the `main` branch.

**Comment by davidbarsky** [comment]
Thanks so much for your work! I just tried out the the changes on the `main` branch, but I'm still getting a similar linker error. At your suggestion, I took a look at the build output, and you were right—there _was_ some sort of warning:

```
removing extension module due to incompatibility: _curses
removing extension module due to incompatibility: _curses_panel
removing extension module due to incompatibility: readline
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
package Flask-1.0.3-py3.7.egg-info does not exist; excluding resources: ["PKG-INFO", "SOURCES.txt", "dependency_links.txt", "entry_points.txt", "installed-files.txt", "not-zip-safe", "requires.txt", "top_level.txt"]
package Jinja2-2.10.1-py3.7.egg-info does not exist; excluding resources: ["PKG-INFO", "SOURCES.txt", "dependency_links.txt", "entry_points.txt", "installed-files.txt", "not-zip-safe", "requires.txt", "top_level.txt"]
package MarkupSafe-1.1.1-py3.7.egg-info does not exist; excluding resources: ["PKG-INFO", "SOURCES.txt", "dependency_links.txt", "installed-files.txt", "top_level.txt"]
package PyYAML-3.13-py3.7.egg-info does not exist; excluding resources: ["PKG-INFO", "SOURCES.txt", "dependency_links.txt", "installed-files.txt", "top_level.txt"]
```

I'll try digging into this a bit more :). It's entirely possible that my slightly weird setup of nixpkgs, macOS, and the fish shell might be doing weird things.

**Comment by indygreg** [comment]
If you run a `pyoxidizer` command with `--verbose`, it will print the verbose output from the `pip` command. And if you look at that output closely, you may find something like:

```
    building '_yaml' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/ext
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/private/var/folders/dd/xb3jz0tj133_hgnvdttctwxc0000gn/T/tmphnt3aknw/deps/include -I/private/var/folders/dd/xb3jz0tj133_hgnvdttctwxc0000gn/T/tmphnt3aknw/deps/lib/libffi-3.2.1/include -I//private/var/folders/dd/xb3jz0tj133_hgnvdttctwxc0000gn/T/tmphnt3aknw/deps/include/ncurses -I/private/var/folders/dd/xb3jz0tj133_hgnvdttctwxc0000gn/T/tmphnt3aknw/deps/include/uuid -DPy_BUILD_CORE_BUILTIN=1 -I/Users/gps/tmp/myapp/build/target/x86_64-apple-darwin/debug/pyoxidizer/python.6668202a3225/python/install/include/python3.7m -I/install/include/python3.7m -c ext/_yaml.c -o build/temp.macosx-10.9-x86_64-3.7/ext/_yaml.o
    In file included from ext/_yaml.c:596:
    ext/_yaml.h:2:10: fatal error: 'yaml.h' file not found
    #include <yaml.h>
             ^~~~~~~~
    1 error generated.
    Error compiling module, falling back to pure Python
```

So essentially `pyyaml`'s build system can't find `yaml.h` and it falls back to not compiling the C extension. This behavior is silent unless you use `--verbose` (which isn't great, but what can you do).

Anyway, if I `brew install libyaml` and build again, `pyyaml` is able to find `yaml.h` and the `_yaml` extension is built and linked into the binary:

```
>>> import _yaml
>>> _yaml
<module '_yaml' (built-in)>
```

So things do work on macOS. It's just that `pyyaml` silently falls back to not building the C extension if a dependency can't be found.

**Comment by davidbarsky** [comment]
Ah, gotcha. Thank you _so_ much for the debugging tip there.

**Comment by davidbarsky** [comment]
You know what, I'm a dummy—I forgot to clean my `build`. Once I did that, everything just worked. Thanks so much!
