### ISSUE TITLE
Certifi Error ( __file__ ) not defined

### ISSUE THREAD

**Issue by jss-cmyk** [indygreg/PyOxidizer#73]
pyapp packaged into /pyapp/build/apps/pyapp/debug
Traceback (most recent call last):
  File "importlib.util", line 94, in find_spec
  File "dpt_installer", line 12, in <module>
  File "requests", line 112, in <module>
  File "requests.utils", line 39, in <module>
  File "certifi.core", line 13, in where
NameError: name '__file__' is not defined

how to solve this problem?
it says can't find module certifi, but with certifi included, it throughs an error

**Comment by indygreg** [comment]
This is because `certifi` assumes that `__file__` must exist. See also #69.

The `certifi` project had an existing issue tracking this matter and I commented there (https://github.com/certifi/python-certifi/issues/66).

**Comment by svenstaro** [comment]
I suppose the possible fix would be to provide a virtual file system which seems like too much of an effort. Hopefully they'll fix it somehow.

**Comment by crabhi** [comment]
@indygreg are you sure `__file__` can be undefined?

PEP 302 in the "Importer Protocol" specifies that

> The __file__ attribute must be set. This must be a string, but it may be a dummy value, for example "<frozen>". The privilege of not having a __file__ attribute at all is reserved for built-in modules.

Certifi would still be broken, but the fix would be a bit different - you can just check whether the path relative to __file__ exists instead of handling `NameError`.

**Comment by crabhi** [comment]
I see the mention at [the import documentation](https://docs.python.org/3/reference/import.html) but they don't say what are the conditions. Therefore, I assume the loaders should all provide it and consumers should not rely on it being present.

> __file__ is optional. If set, this attribute’s value must be a string. The import system may opt to leave __file__ unset if it has no semantic meaning (e.g. a module loaded from a database).

**Comment by indygreg** [comment]
Reading old PEPs can be somewhat misleading because they are point-in-time proposals and aren't updated to reflect an up-to-date specification. I believe the best _specification_ for things like this in Python is CPython's documentation. But even that can be wrong. Ideally there would be a unified language specification and PEPs would update those specifications when they are approved/implemented. But alas.

Anyway, PEP 420 and PEP 451 both make reference to `__file__` being missing or having other quirky behavior. PEP 451 is probably the better read, as it formalized a lot of the low-level components of the modern importing system.

Anyway, if there is further conversation, let's take it to #69. I want that to be the focal point for `__file__` discussions.

**Comment by bbqsrc** [comment]
Given `requests` and `urllib3` both depend on `certifi`, are there any PyOxidizer-compatible HTTP libraries that can be used in the interim? I get need to stream a `GET`, once! 😄

**Comment by crabhi** [comment]
Can you use just plain `urllib` from Python standard library? https://docs.python.org/3/library/urllib.request.html

Or does it depend on `certifi` as well? It looks to me a clean Python installation comes without `certifi`:

```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import certifi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'certifi'
```

**Comment by bbqsrc** [comment]
Oh, I ended up just using `urllib`, yes. I forgot how much `requests` and friends are just syntactic sugar. :D

**Comment by jeamland** [comment]
https://github.com/certifi/python-certifi/pull/116

**Comment by BiatuAutMiahn** [comment]
[https://gitlab.com/alelec/pip-system-certs](https://gitlab.com/alelec/pip-system-certs)
I manually modified requests to use the system certs instead of certifi.

**Comment by indygreg** [comment]
It looks like certifi/python-certifi#116 is now merged, so this is fixed upstream. We still need a new `certifi` release with the new code, however...

I guess we'll keep this open so people can find it.

Thank you for contributing the fix @jeamland!

**Comment by lisxray** [comment]
> It looks like [certifi/python-certifi#116](https://github.com/certifi/python-certifi/pull/116) is now merged, so this is fixed upstream. We still need a new `certifi` release with the new code, however...
> 
> I guess we'll keep this open so people can find it.
> 
> Thank you for contributing the fix @jeamland!

It's still not fixed. The upstream reverted support for PyOxidizer.

Even when I use the `certifi==2020.04.05`, `requests` keeps broken since it fail to read the file whose path is  obtained from `certifi.where()`.

**Comment by lisxray** [comment]
> https://gitlab.com/alelec/pip-system-certs
> I manually modified requests to use the system certs instead of certifi using this patcher

I tried the patcher on both Windows and MacOS, but it didn't work as expected.🤔

**Comment by BiatuAutMiahn** [comment]
What was the issue?

**Comment by manugarri** [comment]
@lisxray did you manage to fix the issue?
